name = "eDisGo_OPF"
uuid = "8c767188-7e8f-4256-9955-fc0aecae9b11"
authors = ["Maike Held"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
#Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
#MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"

[compat]
PowerModels = "0.19.6"
julia = "1.6"
